export const FETCH_PROFILE_REQUESTING = 'FETCH_PROFILE_REQUESTING';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';

export const UPDATE_PROFILE_REQUESTING = 'UPDATE_PROFILE_REQUESTING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
